# Site settings
title: CI
email: contato@joaquimsn.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "hi" # the subpath of your site, e.g. /blog/
url: "http://joaquimsn.com" # the base hostname & protocol for your site

twitter_username:
github_username: joaquimsn

# Build settings
markdown: kramdown

#remote_theme: dp6/dp6.github.io
