name: Build GH-pages

on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          target_branch: 'gh-pages'
          token: ${{ secrets.JEKYLL_PAT }}
      - name: Teste
        run: export JEKYLL_PAT=${{ secrets.JEKYLL_PAT }}
        
