name: Update all github pages

on: [push]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get update && apt install --no-install-recommends -y jq

    - name: Update respositories public with gh-page
      run: sh build-github-pages-dp6.sh ${{ secrets.GH_PAGES_USER }} ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
